'use client'

import EditorialArticle from '@/components/EditorialArticle'

export default function Page() {
  const articleData = {
  "slug": "ai-image-generators",
  "id": "ep-7",
  "emoji": "🎨",
  "image": "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=1600",
  "date": "2026-05-08",
  "readTime": 9,
  "translations": {
    "zh-TW": {
      "title": "AI 圖像生成器：創意產業的毀滅者還是超級增壓器？",
      "subtitle": "當任何人都可以通過文字描述生成專業級插畫，傳統藝術家的價值該如何重新定義？版權爭議又是如何發展的？",
      "sections": [
        {
          "heading": "🖌️ 創作門檻的崩塌",
          "text": "Midjourney 與 Stable Diffusion 的出現，讓視覺傳達不再是少數人的專利。這極大地解放了內容創作者的生產力，但也讓初級插畫師面臨生存危機。"
        },
        {
          "heading": "⚖️ 版權法的灰色地帶",
          "text": "AI 使用版權作品進行訓練是否屬於「合理使用」？目前全球法院仍未達成共識。藝術家們正在發起反擊，要求建立補償機制與防護欄。"
        }
      ],
      "conclusion": "AI 圖像生成不是藝術的終結，而是工具的進化。未來的藝術家將是具備深厚審美觀點並能與 AI 協同創作的人。"
    },
    "en": {
      "title": "AI Image Generators: Destroyer or Supercharger of Creativity?",
      "subtitle": "Navigating the copyright war and the future of digital art.",
      "sections": [
        {
          "heading": "🖌️ Democratization of Art",
          "text": "High-end visuals are now accessible to everyone with a prompt. This is driving a massive wave of innovation in indie gaming, marketing, and web design."
        },
        {
          "heading": "⚖️ The Legal Battle",
          "text": "Who owns an image generated by a machine trained on billions of human works? The legal precedent set today will define the creative industry for the next century."
        }
      ],
      "conclusion": "Art is intent, not just pixels. AI handles the execution, but the vision remains uniquely human."
    },
    "zh-CN": {
      "title": "AI 图像生成器：创意产业冲击",
      "subtitle": "解析生成式AI对艺术创作的影响。",
      "sections": [
        {
          "heading": "🖌️ 生产力革命",
          "text": "AI大幅降低了创作成本，使得大规模个性化视觉内容的生成成为可能。"
        }
      ],
      "conclusion": "拥抱工具，保持审美独特性是未来艺术家的必修课。"
    }
  }
};
  
  return (
    <EditorialArticle 
      id={articleData.id}
      image={articleData.image}
      date={articleData.date}
      readTime={articleData.readTime}
      emoji={articleData.emoji}
      translations={articleData.translations}
    />
  )
}
